/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t volatile *pClockAddress = (uint32_t*) 0x40023830; // Address of RCC (0x40023800) + offset (0x30) to be able to turn on the clock
	uint32_t volatile *pModeRegisterGPIOD = (uint32_t*) 0x40020C00; // Use this address to configure the pin 12->15 of GPIOD that output will pass through them...
	// meaning that the LED will be able to be turned on
	uint32_t volatile *pModeRegisterGPIOA = (uint32_t*) 0x40020000; // Use this address to configure the type of data that will pass on the inputs of GPIOA
	uint32_t volatile *pModeInputGPIOA = (uint32_t*) 0x40020010; // Address where information that is passing through GPIO pins. Here is to read data passing
	uint32_t volatile *pOutputRegisterGPIOD = (uint32_t*) 0x40020C14; // Address to configure the turning on/off of LEDs


	// Enable the clock for GPOID and GPOIA peripheral in the AHB1EN
	// Use the RCC to enable the clock for GPOID and GPOIA to allow of passage of voltage/information
	*pClockAddress |= (1 << 3); // Activate clock in GPIOD to pass voltage to turn on the LEDs
	*pClockAddress |= (1 << 0); // Activate clock in GPIOA to pass voltage to read the data from the pin

	// Configure PD12 as output
	*pModeRegisterGPIOD |= (0b01010101 << 24); // Set the from bit 24 onwards to 01, meaning PD12->PD15 are on output mode...
	// meaning will be able to output/turnOn the LED

	// Configure PA0 as input mode
	*pModeRegisterGPIOA &= ~(3 << 0); // Clear the first two positions of the port a, to set those as INPUT mode

	// Turn on/of the LED
	while(1) {
		uint8_t pintStatus = (uint8_t) (*pModeInputGPIOA & 0x1); // If the first bit is on, it means that voltage is passing through the ping

		if (pintStatus) {
			*pOutputRegisterGPIOD |= (0b1111 << 12); // Activate the LEDs that listen on port 12 onwards (4 LEDs)
		} else {
			*pOutputRegisterGPIOD &= ~(0b1111 << 12); // Use the mask to deactivate only the LEDs that listen on ports 12-15
		}
	}
}
